version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/spring-github-action
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu  # 애플리케이션이 배포될 EC2 경로

hooks:
  hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
 ApplicationStart:
    - location: scripts/start_and_deploy.sh
      timeout: 60
      runas: ec2-user
