name: Java CI with Gradle # Workflow 이름

on:
  push:
    branches: [practice]

env:
  S3_BUCKET_NAME: cammoabucket
  CODE_DEPLOY_APP_NAME: spring-deploy
  CODE_DEPLOY_GROUP_NAME: spring-deploy-group

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash

    - name: Build with Gradle
      run: ./gradlew clean build -x test
      shell: bash

    - name: Make zip file
      run: zip -r ./practice-deploy.zip .
      shell: bash
    
    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws s3 cp --region ap-northeast-2 ./practice-deploy.zip s3://${{ env.S3_BUCKET_NAME }}/practice-deploy.zip

    - name: Code Deploy
      run: aws deploy create-deployment \
        --application-name ${{ env.CODE_DEPLOY_APP_NAME }} \
        --deployment-config-name CodeDeployDefault.AllAtOnce \
        --deployment-group-name ${{ env.CODE_DEPLOY_GROUP_NAME }} \
        --s3-location bucket=${{ env.S3_BUCKET_NAME }},bundleType=zip,key=practice-deploy.zip
